[package]
name = "ioreg"
version = "0.1.0"
authors = ["Zinc Developers <zinc@github.com>", "Geoff Cant <nem@erlang.geek.nz>"]

[lib]
name = "ioreg"
plugin = true

[dev-dependencies.volatile_cell]
git = "https://github.com/archaelus/volatile_cell.git"

[dependencies]
